python HHstudies.py -s GJetPt40toInfDoubleEMEnriched-MGG80toInf -y 17
python HHstudies.py -s ZH-HtoBB-ZtoQQ -y 17
python HHstudies.py -s WplusH-HToBB-WtoQQ -y 17
python HHstudies.py -s GJetsHT200-400 -y 17
python HHstudies.py -s GJetPt20to40DoubleEMEnriched-MGG80toInf -y 17
python HHstudies.py -s ggZH-HtoBB-ZtoQQ -y 17
python HHstudies.py -s VBF-HtoBB -y 17
python HHstudies.py -s WminusH-HToBB-WtoQQ -y 17
python HHstudies.py -s ttH-HtoBB -y 17
python HHstudies.py -s TTToHadronic -y 17
python HHstudies.py -s NMSSM-XToYHTo2g2b-MX-1200MY400 -y 17
python HHstudies.py -s ggH-HtoBB -y 17
python HHstudies.py -s TTTo2L2Nu -y 17
python HHstudies.py -s TTToSemiLeptonic -y 17
python HHstudies.py -s DiPhotonJets-MGG-80toInf -y 17
python HHstudies.py -s GJetsHT400-600 -y 17
python HHstudies.py -s GJetsHT600-Inf -y 17
python HHstudies.py -s NMSSM-XToYHTo2g2b-MX-1200MY60 -y 17
